### ISSUE TITLE
[FEATURE REQUEST] ADDITION OF 'RATING MATTER LESSON' FEATURE ON MOBILE DEVICE.

### ISSUE THREAD

**Issue by Judith0001** [oppia/lessons-team#1462]
After successfully playing through Matter lesson on mobile, learners can not rate the lesson. They are only able to rate the lesson while using a laptop.

STEPS
1. Go to [Matter Lesson 3](https://www.oppia.org/explore/jV513TP7dioq?collection_id=rCxL3LRoFPKh) while using a mobile phone.
2. Play through the lesson until you get to the last card.
3. Notice that you're not able to rate the lesson using a mobile device.

DEVICE USED: Techno Pop 7
Andriod Version 12.
![Screenshot_20240523-124222](https://github.com/oppia/lessons-team/assets/114792791/973c3d81-c137-4af9-a81a-682b950ea248)

**Comment by seanlip** [comment]
@Judith0001 I don't think it's using a mobile device that's the issue here, i think it's because you're not signed in. Without a signed-in session it's hard to tell whether people are submitting multiple ratings.

Could you please check that this works fine after you are signed in on a mobile device? Thanks!

(Closing for now, but feel free to reopen the issue if it still occurs.)
